#!/usr/bin/perl
use v5.10;
use File::Copy;
use File::Find;


sub mvHeaders {
    my ($hdir, $ddir) = @_;

    if (!(-d $ddir)) { mkdir $ddir or die "$!"; }

    opendir my $dh, $hdir or die "oups";
    while(readdir $dh){
        if (/\.h$/) {
            say $_;
            say "$hdir/$_", $ddir;
            copy "$hdir/$_", $ddir or die "cpy: $!";
        }
    }
}


my ($hdir, $ddir, $lib) = @ARGV;
mvHeaders $hdir, $ddir, $lib;
