#!/usr/bin/perl

use v5.10;
use threads;
use threads::shared;
use IO::Handle;

my $target_dir = shift;
my $MAX_THREADS = 4;

# First we find headers files 
my $find_command = "/usr/bin/find $target_dir | grep -e '\\.h\$'";

my $header_files;
$header_files = `$find_command`;
my @hfiles = split /\s/, $header_files;
pop @hfiles;
my $nbfiles = $#hfiles;
say "$nbfiles files to parse.";

my @jobs;

open($fh, ">output.xml") or die "cannot open output file"; 

say $fh "<root>";

my $j :shared;
my $mutex_write :shared;

$j = 0;
for (my $i = 0; $i < $MAX_THREADS; $i++)
{
    push @jobs, threads->create(sub{
            my $run = 1;
            while($run)
            {
                my $file;
                {
                    lock($j);
                    if ($j > $#hfiles){ $run = 0; }
                    else{
                        $file = $hfiles[$j];
                        $j++;
                        say "--$j -> $file--";
                    }
                }
                if($run){
                    my $command = "/usr/bin/perl cscan --lazy --get parsed_fdecls $file";
                    my $xml = `$command`;

                    my $ind = index($xml, ">") + 1;
                    $xml = substr($xml, $ind, (length $xml) - $ind);

                    say "Writing...";
                    {
                        lock($mutex_write);
                        print $fh $xml;
                        $fh->flush();
                    }
                    say "Parsing $file: done.";
                }
            }
        });
}

$_->join for @jobs;
say $fh "</root>";


