#!/usr/bin/perl

use v5.10;

use File::Copy::Recursive qw(dircopy);
use File::Copy;
use Data::Dumper;

sub isLib {
    my ($libInDB) = @_;

    $cmd = "g++ $libInDB->{test} -L$libInDB->{tmpDir} -I$libInDB->{hDir} $libInDB->{compopt}";
    say $cmd;
    return (system($cmd) == 0);
}


sub genTmpDir { 
    my ($libToCheck, $libToReplace, $libInDB) = @_;

    dircopy $libInDB->{soDir},$libInDB->{tmpDir} or die "$libInDB->{soDir}: $!";
    copy $libToCheck, "$libInDB->{tmpDir}/$libToReplace";
}


sub genEntry {
    my ($folder) = @_;
    my %libToCreate;

    open my $name, "<", "$folder/name.txt" or die "$!";
    $libToCreate{name} = <$name>;
    close $name;

    open my $version, "<", "$folder/version.txt" or die "$!";
    $libToCreate{version} = <$version>;
    close $version;

    $libToCreate{hDir} = "$folder/headers";
    $libToCreate{soDir} = "$folder/so";
    $libToCreate{tmpDir} = "$folder/tmp";
    $libToCreate{test} = "$folder/test.c";

    if (!(-d $libToCreate{tmpDir})) { mkdir $libToCreate{tmpDir}; }

    return \%libToCreate;
}


my %libStored = (
    name => 'openssl',
    version => 1.0.0,
    compopt => '-lwouhou',
    test => './test.c', 
    soDir => './so', 
    tmpDir => './tmp',
    hDir => './headers'
);


my $NumberOfMandatoryParameters = 2;
if ($#ARGV + 1 != $NumberOfMandatoryParameters) {die "Wrong parameters";}
my ($libToCheck, $folderLibDB) = @ARGV;


my $libDB = genEntry $folderLibDB;
say Dumper($libDB);
# say Dumper(\%libStored);

opendir my $dir, $libDB->{soDir} or die "$!";
while(my $file = readdir $dir) {
    if ($file =~ /\.so$/){
        genTmpDir $lib, $file, $libDB; 
        if(isLib $libDB) {
            say "Youhou !";
        }
    }
}
close $dir;
